name: SignsOfLife

on:
  push:
    branches:
      - main
jobs:
  notify-the-world:
    steps:
    - name: MQTT the client information
      uses: juhrlass/mqtt-action@master
      with:
      protocol: mqtt
      host: mqtt.dynamicdevices.co.uk
      port: 1883
      topic: "signsoflife"
      message: ${{ github.sha }}
